### ISSUE TITLE
Error when I click on Run

### ISSUE THREAD

**Issue by alexfredo** [CiaraStrawberry/TemporalKit#1]
I have installed the requirements but I have a error after I add the video I click on Run : 

reading video file... C:\Users\Alex\AppData\Local\Temp\b20b8b368a0dab613dda4605c6b78ea96b90de0c\ghostingtest.mp4
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AUTOMATIC1111\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\AUTOMATIC1111\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AUTOMATIC1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AUTOMATIC1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AUTOMATIC1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 54, in preprocess_video
    image = berry.generate_square_from_video(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side )
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\Berry_Method.py", line 128, in generate_square_from_video
    frames = extract_frames_movpie(video_data, fps, frames_limit)
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\Berry_Method.py", line 491, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\Berry_Method.py", line 483, in get_video_info
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by CiaraStrawberry** [comment]
Are you sure the video is added and exists? Did you give it a second after running to make sure?

**Comment by alexfredo** [comment]
I have checked with "py -m pip freeze" if the requirements are installed too

**Comment by CiaraStrawberry** [comment]
O.o I see what you mean, that's weird, maybe it's the fact I basically always drag and drop the videos in when I test, I'll try click upload on my side.

That or i assumed the video was always going to be .mp4 or something somewhere, what format is your video?

**Comment by CiaraStrawberry** [comment]
And i have confirmed the click upload works fine on my side, can you send over the mp4 video file you're trying to use?

**Comment by CiaraStrawberry** [comment]
Thanks! works on my side too, really weird, only thing it must be is an incompatibility between your system and this code:

    with tempfile.NamedTemporaryFile(suffix='.mp4', delete=False) as f:
        f.write(input_video)
    video_path = f.name

hmm

**Comment by CiaraStrawberry** [comment]
wait ooooooo, i think you might need to install ffmpeg

**Comment by alexfredo** [comment]
Ok I try the tutorial

**Comment by alexfredo** [comment]
It's works you are awesome 👍

**Comment by CiaraStrawberry** [comment]
:D Great to hear, thanks for the files and notes, really helps.

Quick hint too, if you want a video with as quick movement as that, you're gonna want a relatively high fps in the settings.
