### ISSUE TITLE
Tqdm issue

### ISSUE THREAD

**Issue by alpaolo** [CiaraStrawberry/TemporalKit#113]
Hi Ciara, how can I overcome the problem of moviepy wanting an older version of Tqdm and breaking the Automatic 1111 installation?

**Comment by cocomine** [comment]
Please see the FAQ section: https://github.com/CiaraStrawberry/TemporalKit#faq

**Comment by taellinglin** [comment]
I have done this, installed pip install tqdm==4.66.1

It now says:
PS D:\sdwebui> .\webui-user.bat
venv "D:\sdwebui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments:
Traceback (most recent call last):
  File "D:\sdwebui\launch.py", line 48, in <module>
    main()
  File "D:\sdwebui\launch.py", line 44, in main
    start()
  File "D:\sdwebui\modules\launch_utils.py", line 432, in start
    import webui
  File "D:\sdwebui\webui.py", line 13, in <module>
    initialize.imports()
  File "D:\sdwebui\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "D:\sdwebui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\sdwebui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\sdwebui\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "D:\sdwebui\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "D:\sdwebui\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "D:\sdwebui\venv\lib\site-packages\huggingface_hub\__init__.py", line 357, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\User\miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\sdwebui\venv\lib\site-packages\huggingface_hub\hf_api.py", line 59, in <module>
    from ._commit_api import (
  File "D:\sdwebui\venv\lib\site-packages\huggingface_hub\_commit_api.py", line 15, in <module>
    from tqdm.contrib.concurrent import thread_map
ModuleNotFoundError: No module named 'tqdm.contrib'
Press any key to continue . . .

**Comment by taellinglin** [comment]
I also uninstalled old version of tqdm

**Comment by cocomine** [comment]
I've fixed it but since I don't have direct access to this repository, you can temporarily use my forked version https://github.com/cocomine/TemporalKit.
Once I've fully tested it and confirmed it's ok I will open a pull request. If you encounter any problems using my forked version, please submit an issue at https://github.com/cocomine/TemporalKit/issues/new/choose.
