### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Jasonforai777** [CiaraStrawberry/TemporalKit#132]
reading video file... C:\Users\ADMINI~1\AppData\Local\Temp\gradio\bb7a780454371320622fb45b3e739c00d8471fcb\test.mp4
Interpolating extra frames with max frames 450000 and interpolating = False
Traceback (most recent call last):
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\sd-webui-aki-v4.2\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 93, in preprocess_video
    existing_frames = [sd_utility.extract_frames_movpie(data, fps,max_frames=max_total_frames,perform_interpolation=False)]
  File "F:\sd-webui-aki-v4.2\extensions\TemporalKit\scripts\berry_utility.py", line 640, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "F:\sd-webui-aki-v4.2\extensions\TemporalKit\scripts\berry_utility.py", line 629, in get_video_info
    return json.loads(result.stdout)
  File "F:\sd-webui-aki-v4.2\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "F:\sd-webui-aki-v4.2\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\sd-webui-aki-v4.2\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by BESTrdAS** [comment]
我也有这个报错，看了一下配置，环境变量也配置了，打印报错日志执行的命令行，在cmd模式下可以执行，后面我就改成了不通过环境变量执行ffprobe，直接写绝对路径执行，就ok了。berry_utility，extract_frames_movpie函数
![Snipaste_2024-05-04_22-12-34](https://github.com/CiaraStrawberry/TemporalKit/assets/26713366/39d9bc84-0765-4f62-a11a-61cb73bd2643)
