### ISSUE TITLE
Automatic1111 cannot load Temporal Kit

### ISSUE THREAD

**Issue by tymc007** [CiaraStrawberry/TemporalKit#136]
Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\temporalKit\scripts\sd-TemporalKit-UI.py", line 44, in <module>
        import scripts.Ebsynth_Processing as ebsynth
      File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\temporalKit\scripts\Ebsynth_Processing.py", line 10, in <module>
        import extensions.TemporalKit.scripts.berry_utility
    ModuleNotFoundError: No module named 'extensions.TemporalKit'

**Comment by cocomine** [comment]
I'm waiting for the owner to approve the merge, as a short term solution you can use my forked version first https://github.com/cocomine/TemporalKit

**Comment by qingsongxi** [comment]
I had the same problem on my mac

WebUI version: v1.10.1
Python version: 3.10.15
torch: 2.3.1
xformers: N/A
gradio: 3.41.2

The following error message is displayed during startup:
*** Error loading script: Berry_Method.py
*** Error loading script: Ebsynth_Processing.py
*** Error loading script: berry_utility.py
*** Error loading script: optical_flow_raft.py
*** Error loading script: optical_flow_simple.py
*** Error loading script: sd-TemporalKit-UI.py
*** Error loading script: stable_diffusion_processing.py
