### ISSUE TITLE
TemporalKit get error

### ISSUE THREAD

**Issue by Castor9133** [CiaraStrawberry/TemporalKit#137]
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 93, in preprocess_video
    existing_frames = [sd_utility.extract_frames_movpie(data, fps,max_frames=max_total_frames,perform_interpolation=False)]
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\TemporalKit\scripts\berry_utility.py", line 640, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\TemporalKit\scripts\berry_utility.py", line 629, in get_video_info
    return json.loads(result.stdout)
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Castor9133** [comment]
To create a public link, set `share=True` in `launch()`.
Startup time: 40.0s (prepare environment: 13.6s, import torch: 5.7s, import gradio: 0.7s, setup paths: 0.4s, initialize shared: 0.8s, other imports: 0.4s, load scripts: 12.3s, create ui: 3.7s, gradio launch: 2.2s).
ERROR:pyscenedetect:VideoManager is deprecated and will be removed.
INFO:pyscenedetect:Loaded 1 video, framerate: 30.000 FPS, resolution: 1280 x 720
INFO:pyscenedetect:Downscale factor set to 5, effective resolution: 256 x 144
INFO:pyscenedetect:Detecting scenes...
Detected 1 scenes
Processing scene 1: start_frame=0, end_frame=239 original fps=30.0 target fps=30
Scene 1 has 240 frames with length of 240 frames with the old duration of 239 frames
Total scenes: 1
frame_groups 240
overlap group size 10
overlap group size 10
 trim_imagestransitions [0, 1]
frames_total_size = 3, frames batch size = 90 array length = 3
splitting video 0
[MoviePy] >>>> Building video D:\FFOutput\0\input_video.mp4
[MoviePy] Writing video D:\FFOutput\0\input_video.mp4
[MoviePy] Done.
[MoviePy] >>>> Video ready: D:\FFOutput\0\input_video.mp4

splitting video 1
[MoviePy] >>>> Building video D:\FFOutput\1\input_video.mp4
[MoviePy] Writing video D:\FFOutput\1\input_video.mp4
[MoviePy] Done.
[MoviePy] >>>> Video ready: D:\FFOutput\1\input_video.mp4

splitting video 2
[MoviePy] >>>> Building video D:\FFOutput\2\input_video.mp4
[MoviePy] Writing video D:\FFOutput\2\input_video.mp4
[MoviePy] Done.
[MoviePy] >>>> Video ready: D:\FFOutput\2\input_video.mp4

reading video file... D:\FFOutput\0\input_video.mp4
Interpolating extra frames with max frames None and interpolating = False
Traceback (most recent call last):
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sdwebuiaki\sdwebuiaki\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 99, in preprocess_video
    generated_textures = General_SD.generate_squares_to_folder(individual_video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side,max_frames=None, output_folder=os.path.dirname(individual_video),border=0, ebsynth_mode=ebsynth_mode,max_frames_to_save=max_frames)
  File "D:\sdwebuiaki\sdwebuiaki\extensions\TemporalKit\scripts\Berry_Method.py", line 222, in generate_squares_to_folder
    frames = utilityb.extract_frames_movpie(video_data, fps, max_frames,False)
  File "D:\sdwebuiaki\sdwebuiaki\extensions\TemporalKit\scripts\berry_utility.py", line 640, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "D:\sdwebuiaki\sdwebuiaki\extensions\TemporalKit\scripts\berry_utility.py", line 624, in get_video_info
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
 File "D:\sdwebuiaki\sdwebuiaki\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 217, in sentry_patched_popen_init
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\sdwebuiaki\sdwebuiaki\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] access denied.

I switch the version of SD and then a brand new error.

**Comment by cocomine** [comment]
I'm waiting for the owner to approve the merge, as a short term solution you can use my forked version first https://github.com/cocomine/TemporalKit

**Comment by BESTrdAS** [comment]
我也有这个报错，看了一下配置，环境变量也配置了，打印报错日志执行的命令行，在cmd模式下可以执行，后面我就改成了不通过环境变量执行ffprobe，直接写绝对路径执行，就ok了。berry_utility，extract_frames_movpie函数 
![Snipaste_2024-05-04_22-12-34](https://github.com/CiaraStrawberry/TemporalKit/assets/26713366/e9bd8e39-c0de-41f2-95ba-1b420d4482c0)
