### ISSUE TITLE
TemporalKit don´t load after AUTOMATIC1111 stable-diffusion-webui update 1.9.0

### ISSUE THREAD

**Issue by Yuugenbrose** [CiaraStrawberry/TemporalKit#139]
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import  create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (E:\stable-diffusion-webui\modules\ui.py)

**Comment by BigShaka77** [comment]
me too, any solution?

**Comment by QuestPanel** [comment]
had the same problem. fixed my issue by opening `...\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py` , with notepad, and then changed the line `from modules.ui import  create_sampler_and_steps_selection` 
with
 `from modules.ui import  create_setting_component`

**Comment by wushifen** [comment]
> 有同样的问题。通过打开 来解决我的问题 记事本，然后用`...\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py``from modules.ui import create_sampler_and_steps_selection` `from modules.ui import create_setting_component`

Thank you, I succeeded using your ideas

**Comment by joegoldin** [comment]
see: https://github.com/CiaraStrawberry/TemporalKit/issues/134

**Comment by darkdarkcocoa** [comment]
> > 有同样的问题。通过打开 来解决我的问题 记事本，然后用`` ...\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py``from modules.ui import create_sampler_and_steps_selection `` `from modules.ui import create_setting_component`
> 
> Thank you, I succeeded using your ideas

thank you

**Comment by NoticeVengus** [comment]
it worked and THX !!!

**Comment by Dohrah** [comment]
> had the same problem. fixed my issue by opening `...\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py` , with notepad, and then changed the line `from modules.ui import create_sampler_and_steps_selection` with `from modules.ui import create_setting_component`

@QuestPanel  I spent the last 3 hours trying out the solutions on the Internet and this is the only thing that fixed it. THANK YOU!!!!

**Comment by doumaocm** [comment]
不起作用，这个方法根本行不通

**Comment by TheSketty** [comment]
> had the same problem. fixed my issue by opening `...\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py` , with notepad, and then changed the line `from modules.ui import create_sampler_and_steps_selection` with `from modules.ui import create_setting_component`

cool and all but... this function isn't even used in this file, so why couldn't I just delete this import?
