### ISSUE TITLE
update SD1.9,bug.  ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (M:\SD\sdwebui\modules\ui.py)

### ISSUE THREAD

**Issue by swumagic** [CiaraStrawberry/TemporalKit#140]
update SD1.9,bug. 
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import  create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (M:\SD\sdwebui\modules\ui.py)

---
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: face_editor.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-face-editor\scripts\face_editor.py", line 6, in <module>
        from scripts.ui.ui_builder import UiBuilder
    ModuleNotFoundError: No module named 'scripts.ui.ui_builder'; 'scripts.ui' is not a package

---
*** Error loading script: face_editor_extension.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-face-editor\scripts\face_editor_extension.py", line 5, in <module>
        from scripts.ui.ui_builder import UiBuilder
    ModuleNotFoundError: No module named 'scripts.ui.ui_builder'; 'scripts.ui' is not a package

**Comment by aleksbos** [comment]
> обновить SD1.9, ошибка. *** Ошибка сценария загрузки: sd-TemporalKit-UI.py Обратная трассировка (последний вызов): файл "M:\SD\sdwebui\modules\scripts.py", строка 508, в load_scripts script_module = script_loading.load_module(scriptfile.path) Файл "M:\SD\sdwebui\modules\script_loading.py", строка 14, в load_module module_spec.loader.exec_module(модуль) Файл "", строка 883, в exec_module файл "", строка 241, в _call_with_frames_removed файл "M:\SD\sdwebui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", строка 23, в из modules.ui import create_sampler_and_steps_selection ImportError: не удается импортировать имя 'create_sampler_and_steps_selection' из 'modules.ui' (M:\SD\sdwebui\modules\ui.py)
> 

A similar problem

**Comment by gonglaijiang** [comment]
so ,can anybody try to solve this problem?
i have a similar problem,too

*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "F:\SD_2024\sd.webui\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\SD_2024\sd.webui\webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\SD_2024\sd.webui\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import  create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (F:\SD_2024\sd.webui\webui\modules\ui.py)

**Comment by baiyan0817** [comment]
same question
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import  create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (E:\AI\stable-diffusion-webui\modules\ui.py)

**Comment by ch-xiaoc** [comment]
compatibility issues,change sd1.8  can solved

**Comment by TommyWinstonHawes** [comment]
Help my brain hurts. Been running the same script for 4 hours straight, I could have used this time to touch grass but instead, I've been looking at PowerShell terminal. I'm about 10 minutes away from selling my computer to a slab of concrete 100m below my window.

![image](https://github.com/CiaraStrawberry/TemporalKit/assets/132183877/d97d5e3e-f619-4cd0-be9f-ed83ed2b3fe2)

![image](https://github.com/CiaraStrawberry/TemporalKit/assets/132183877/5b6a839f-5e30-4dcb-85b8-87af53091245)

**Comment by joegoldin** [comment]
see: https://github.com/CiaraStrawberry/TemporalKit/issues/134

**Comment by joegoldin** [comment]
@TommyWinstonHawes 
> Help my brain hurts. Been running the same script for 4 hours straight, I could have used this time to touch grass but instead, I've been looking at PowerShell terminal. I'm about 10 minutes away from selling my computer to a slab of concrete 100m below my window.

see: https://github.com/CiaraStrawberry/TemporalKit/issues/134

**Comment by hufang168808** [comment]
why？

Joe Goldin ***@***.***> 于 2024年5月1日周三 05:48写道：

**Comment by TommyWinstonHawes** [comment]
> @TommyWinstonHawes
> 
> > Help my brain hurts. Been running the same script for 4 hours straight, I could have used this time to touch grass but instead, I've been looking at PowerShell terminal. I'm about 10 minutes away from selling my computer to a slab of concrete 100m below my window.
> 
> see: #134

thanks replacing line 23 with "from modules.ui import  create_setting_component" worked
