### ISSUE TITLE
 ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui'

### ISSUE THREAD

**Issue by tangA008** [CiaraStrawberry/TemporalKit#142]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.0
Commit hash: c19d04436496ab29ddca4758a792831ae41b31de
Installing requirements
current transparent-background 1.3.2
is_installed check for tensorflow-cpu failed as 'spec is None'
Installing requirements for easyphoto-webui
Installing requirements for tensorflow
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.02157459999943967
CUDA 11.8
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch --skip-python-version-check
CHv1.8.11: Get Custom Model Folder
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.9\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd-webui-aki-v4.9\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd-webui-aki-v4.9\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import  create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (E:\sd-webui-aki-v4.9\modules\ui.py)

replacing line 23 with "from modules.ui import create_setting_component",Unable to resolve the issue

**Comment by huggenbe** [comment]
EDIT:
The better fix is probably this: 
Navigate to `sd.webui/webui/extensions/TemporalKit/scripts/`, open sd-TemporalKit-UI.py and change the line 23 from `from modules.ui import  create_sampler_and_steps_selection` to `from modules.ui import  create_setting_component.`


Another way to fix it:

I had the same error. 

The issue arises because Automatic1111 removed the function "create_sampler_and_steps_selection" from their ui.py file. You can fix it by manually adding it yourself again. That at least resolved the issue for me and I can see TemporalKit now. 

I haven't had the time testing if this breaks anything yet but I at least got it running.

To fix it for yourself: Navigate to` sd.webui/webui/modules/` and find the ui.py file. 
Add 
```
def create_sampler_and_steps_selection(choices, tabname):
    if opts.samplers_in_dropdown:
        with FormRow(elem_id=f"sampler_selection_{tabname}"):
            sampler_name = gr.Dropdown(label='Sampling method', elem_id=f"{tabname}_sampling", choices=choices, value=choices[0])
            steps = gr.Slider(minimum=1, maximum=150, step=1, elem_id=f"{tabname}_steps", label="Sampling steps", value=20)
    else:
        with FormGroup(elem_id=f"sampler_selection_{tabname}"):
            steps = gr.Slider(minimum=1, maximum=150, step=1, elem_id=f"{tabname}_steps", label="Sampling steps", value=20)
            sampler_name = gr.Radio(label='Sampling method', elem_id=f"{tabname}_sampling", choices=choices, value=choices[0])

    return steps, sampler_name
```
to the file somewhere on base level (not inside another function). This is the old function I grabbed from Automatic1111's ui.py history.

Hope that helps.

**Comment by bit9labs** [comment]
Can confirm the workaround by @huggenbe works.

**Comment by Thomatelot** [comment]
> EDIT: The better fix is probably this: Navigate to `sd.webui/webui/extensions/TemporalKit/scripts/`, open sd-TemporalKit-UI.py and change the line 23 from `from modules.ui import create_sampler_and_steps_selection` to `from modules.ui import create_setting_component.`
> 
> Another way to fix it:
> 
> I had the same error.
> 
> The issue arises because Automatic1111 removed the function "create_sampler_and_steps_selection" from their ui.py file. You can fix it by manually adding it yourself again. That at least resolved the issue for me and I can see TemporalKit now.
> 
> I haven't had the time testing if this breaks anything yet but I at least got it running.
> 
> To fix it for yourself: Navigate to` sd.webui/webui/modules/` and find the ui.py file. Add
> 
> ```
> def create_sampler_and_steps_selection(choices, tabname):
>     if opts.samplers_in_dropdown:
>         with FormRow(elem_id=f"sampler_selection_{tabname}"):
>             sampler_name = gr.Dropdown(label='Sampling method', elem_id=f"{tabname}_sampling", choices=choices, value=choices[0])
>             steps = gr.Slider(minimum=1, maximum=150, step=1, elem_id=f"{tabname}_steps", label="Sampling steps", value=20)
>     else:
>         with FormGroup(elem_id=f"sampler_selection_{tabname}"):
>             steps = gr.Slider(minimum=1, maximum=150, step=1, elem_id=f"{tabname}_steps", label="Sampling steps", value=20)
>             sampler_name = gr.Radio(label='Sampling method', elem_id=f"{tabname}_sampling", choices=choices, value=choices[0])
> 
>     return steps, sampler_name
> ```
> 
> to the file somewhere on base level (not inside another function). This is the old function I grabbed from Automatic1111's ui.py history.
> 
> Hope that helps.

Hello, I can't fix this issue even after what you said that I applied in SD.
Here is what I got : 

WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\TemporalKitImg2ImgTab.py:47: GradioDeprecationWarning: unexpected argument for Button: label
  savebutton = gr.Button("save", label="Save")

WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\TemporalKitImg2ImgTab.py:51: GradioDeprecationWarning: unexpected argument for Button: label
  movebutton = gr.Button("move", label="Move")

2024-10-19 17:56:45,581 - ControlNet - INFO - ControlNet UI callback registered.
WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:374: GradioDeprecationWarning: unexpected argument for Video: type
  video = gr.Video(label="Input Video", elem_id="input_video",type="filepath")

WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:391: GradioDeprecationWarning: unexpected argument for Number: placeholder
  max_keyframes = gr.Number(value=-1, label="Max key frames", precision=1, interactive=True,placeholder="for all frames")

WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:392: GradioDeprecationWarning: unexpected argument for Number: placeholder
  border_frames = gr.Number(value=2, label="Border Key Frames", precision=1, interactive=True,placeholder="border frames")

WARNING:py.warnings:D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:405: GradioDeprecationWarning: unexpected argument for Tabs: elemn_id
  with gr.Tabs(elemn_id="TemporalKit_gallery_container"):

*** Error executing callback ui_tabs_callback for D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 569, in on_ui_tabs
        create_video_Processing_Tab()
      File "D:\00_PERSO\Outils IA\Stable Diffusion\SD Forge Refresh\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 408, in create_video_Processing_Tab
        result_image = gr.outputs.Image(type='pil')
    AttributeError: module 'gradio' has no attribute 'outputs'
