### ISSUE TITLE
temporal kit tab doesnt show up

### ISSUE THREAD

**Issue by Kuncuperzz** [CiaraStrawberry/TemporalKit#145]
i dont have phyton basic, my temporalkit tab doesnt show up after i installed,
can some one help

here the command prompt fault
*** Error loading script: sd-TemporalKit-UI.py
    Traceback (most recent call last):
      File "D:\Stable Difusion A1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Stable Difusion A1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Stable Difusion A1111\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 23, in <module>
        from modules.ui import create_sampler_and_steps_selection
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (D:\Stable Difusion A1111\stable-diffusion-webui\modules\ui.py)

**Comment by doumaocm** [comment]
有解决的吗？一模一样的报错，无法显示前端；
