### ISSUE TITLE
Errors executing it!

### ISSUE THREAD

**Issue by merecesarchviz** [CiaraStrawberry/TemporalKit#16]
Hi Ciara,

I installed you extension but when i try to run it it get a lot of errors! any idead what they are about and can solve it? thks

reading video file... C:\Users\Ryzen_Reaper\AppData\Local\Temp\879953c216bc574e66d9db11f04de5ccd3c2b905\ORIGINAL SOURCE.mp4████████████████████████████████████| 20/20 [00:02<00:00,  8.69it/s]
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\SD\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 65, in preprocess_video
    image = berry.generate_square_from_video(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side )
  File "F:\SD\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 168, in generate_square_from_video
    frames = extract_frames_movpie(video_data, fps, frames_limit)
  File "F:\SD\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 581, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "F:\SD\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 568, in get_video_info
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] O sistema não conseguiu localizar o ficheiro especificado

**Comment by CiaraStrawberry** [comment]
Hi! This is saying you don't have ffmpeg installed to path, follow this guide: 

https://www.wikihow.com/Install-FFmpeg-on-Windows

I really should add a try catch that says this to help.

**Comment by merecesarchviz** [comment]
I have it, but is not added in the system enviroment, now workng, thks
