### ISSUE TITLE
Is TemporalKit v1.3 ready to install ?

### ISSUE THREAD

**Issue by alexfredo** [CiaraStrawberry/TemporalKit#21]
Hi I have downloaded the branch "scenes_and_multi_runs" and I have a error message after install it
Here the bug ( I have installed the scenedetect module ) :

To create a public link, set `share=True` in `launch()`.
Startup time: 4.1s (load scripts: 0.6s, create ui: 3.0s, gradio launch: 0.4s).
Closing server running on port: 7860
Restarting UI...
Error loading script: Ebsynth_Processing.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AUTOMATIC1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\Ebsynth_Processing.py", line 10, in <module>
    import extensions.TemporalKit.scripts.berry_utility
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\berry_utility.py", line 20, in <module>
    import scenedetect
ModuleNotFoundError: No module named 'scenedetect'

Error loading script: berry_utility.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AUTOMATIC1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AUTOMATIC1111\extensions\TemporalKit\scripts\berry_utility.py", line 20, in <module>
    import scenedetect
ModuleNotFoundError: No module named 'scenedetect'

**Comment by CiaraStrawberry** [comment]
Technically not yet, had way more edge case bugs left that i assumed, done now and pushing in a sec to the main branch although i hadn't realised id forgotten to commit the install.py changes i made so you saved me some fuss :D
