### ISSUE TITLE
Temporal-Warp: ImageSequenceClip requires all images to be the same size

### ISSUE THREAD

**Issue by merodiro** [CiaraStrawberry/TemporalKit#26]
When running Temporal-Warp I got this error

I'm using `moviepy==2.0.0.dev2` because the latest stable version gave me this error #24 so this might be related to the issue

```
Traceback (most recent call last):
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/coder/automatic/extensions/TemporalKit/scripts/sd-TemporalKit-UI.py", line 128, in apply_image_to_video
    return General_SD.process_video_single(video_path=video,fps=fps,per_side=per_side,batch_size=batch_size,fillindenoise=0,edgedenoise=0,_smol_resolution=output_resolution,square_texture=image)
  File "/home/coder/automatic/extensions/TemporalKit/scripts/Berry_Method.py", line 340, in process_video_single
    generated_video =  utilityb.pil_images_to_video(processed_frames, output_video_path, fps)
  File "/home/coder/automatic/extensions/TemporalKit/scripts/berry_utility.py", line 509, in pil_images_to_video
    clip = ImageSequenceClip(np_images, fps=fps)
  File "/home/coder/automatic/venv/lib/python3.10/site-packages/moviepy/video/io/ImageSequenceClip.py", line 95, in __init__
    raise Exception(
Exception: Moviepy: ImageSequenceClip requires all images to be the same size
```
Edit: I tried with the stable `moviepy` version and got the same error

**Comment by CiaraStrawberry** [comment]
This bug pains me so hard, can you try zipping the project (location you paste everywhere) folder and upload it here and tell me which button clicking causes this for you?

**Comment by merodiro** [comment]
When I tried to make a project to zip it and used Batch-Warp it worked with the same video and settings
