### ISSUE TITLE
Berry_Method.py error on load and no TemporalKit tab

### ISSUE THREAD

**Issue by darthsnarkey** [CiaraStrawberry/TemporalKit#28]
I keep getting this error on load, using Vadmandic, also not working in Automatic1111. I install but no tab ever shows up.

Error loading script: Berry_Method.py
Traceback (most recent call last):
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 7, in <module>
    import scripts.stable_diffusion_processing as sdprocess
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\TemporalKit\scripts\stable_diffusion_processing.py", line 15, in <module>
    import scripts.optical_flow_raft as raft
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\TemporalKit\scripts\optical_flow_raft.py", line 23, in <module>
    model = raft_large(weights=Raft_Large_Weights.DEFAULT, progress=False).to(device)
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torchvision\models\_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torchvision\models\_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torchvision\models\optical_flow\raft.py", line 836, in raft_large
    return _raft(
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torchvision\models\optical_flow\raft.py", line 805, in _raft
    model.load_state_dict(weights.get_state_dict(progress=progress))
  File "D:\SD\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1624, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

**Comment by darthsnarkey** [comment]
This error was thrown due to an incomplete download of a checkpoint, I recommend downloading it manually and placing it in the folder.
