### ISSUE TITLE
Error with launch

### ISSUE THREAD

**Issue by hoolswelsh** [CiaraStrawberry/TemporalKit#32]
Interpolating extra frames
Traceback (most recent call last):
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 118, in preprocess_video
    image = General_SD.generate_square_from_video(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side )
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 170, in generate_square_from_video
    frames = utilityb.extract_frames_movpie(video_data, fps, frames_limit)
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\TemporalKit\scripts\berry_utility.py", line 633, in extract_frames_movpie
    video_info = get_video_info(video_path)
  File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\TemporalKit\scripts\berry_utility.py", line 622, in get_video_info
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

I have this error and I've tried obvious solutions and can't debug the issue, do you have any suggestions.

**Comment by CiaraStrawberry** [comment]
FFMPEG isn't installed to path (or to the right bit of path)

follow this: https://phoenixnap.com/kb/ffmpeg-windows
