### ISSUE TITLE
Error when Running

### ISSUE THREAD

**Issue by howitzer99** [CiaraStrawberry/TemporalKit#33]
I'm having issues when running the script.  Initially I saw these errors, and wasn't able to get it to work until I restarted about 3 times, then I was able to run the script once and the script did generate keyframes.  When I adjust the keyframes to "-1" and pressed run again, the errors came back. When these error occue, I need to shutdown web-ui at that point (hangs).

I have "git --pull" enabled, so I'm running the latest build of a1111 web-ui.

Traceback (most recent call last):
  File "E:\StableDiffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\StableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\StableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\StableDiffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\StableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\StableDiffusion\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 115, in preprocess_video
    return image[0]
IndexError: list index out of range

**Comment by CiaraStrawberry** [comment]
Screenshot your settings please so I can test

**Comment by howitzer99** [comment]
The test I'm running is 40 frames, and the tutorial I went over stated that "Split Video" wasn't needed for this number of frames.  Though, with "Split Video" disabled, the errors above occur.  With it enabled, it seems to run, even though the output video in the web ui shows "Error".

![Screenshot_80](https://user-images.githubusercontent.com/13814276/235278765-1fba7603-f754-472a-ba95-b9096c610fb8.jpg)
![Screenshot_81](https://user-images.githubusercontent.com/13814276/235278769-ab55549b-ac82-4279-957c-1318bcfc28fb.jpg)

**Comment by CiaraStrawberry** [comment]
I've seen a few people run into this, but i've never hit it on my side, maybe it's the lengths of my video clips

**Comment by CiaraStrawberry** [comment]
yep, there's the issue, all my testing clips are quite long, gonna fix now

**Comment by CiaraStrawberry** [comment]
fixed ^^, shout me if it's still broken but should be all good now

**Comment by howitzer99** [comment]
Thanks for your help, it's working as expected now.

Cheers.
