### ISSUE TITLE
Error on launch, not tab appears

### ISSUE THREAD

**Issue by GabrielMSharp** [CiaraStrawberry/TemporalKit#36]
Have just fresh installed into automatic1111.

Getting multiple errors on launch, all around model downloads from pytorch it seems.

```
Downloading: "https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth" to C:\Users\Gabriel/.cache\torch\hub\checkpoints\raft_large_C_T_SKHT_V2-ff5fadd5.pth
Error loading script: Berry_Method.py
Traceback (most recent call last):
  File "C:\Users\Gabriel\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open

[...]

 File "C:\Users\Gabriel\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by GabrielMSharp** [comment]
I was able to fix this by manually downloading and moving to the folder. Unclear why the cli couldn't get through,.

**Comment by CiaraStrawberry** [comment]
Thanks for the info, might be a network issue.

**Comment by kianma42** [comment]
> I was able to fix this by manually downloading and moving to the folder. Unclear why the cli couldn't get through,.

please tell me how?
