### ISSUE TITLE
Please ensure that ffmpeg is installed and available in your system's PATH.

### ISSUE THREAD

**Issue by viveksp1432** [CiaraStrawberry/TemporalKit#40]
Please ensure that ffmpeg isInterpolating extra frames with max frames 450000 and interpolating = False
Error: [WinError 2] The system cannot find the file specified. Please ensure that ffmpeg is installed and available in your system's PATH.
Traceback (most recent call last):
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 93, in preprocess_video
    existing_frames = [sd_utility.extract_frames_movpie(data, fps,max_frames=max_total_frames,perform_interpolation=False)]
  File "D:\Stable_diffusion SD 1.5\stable-diffusion-webui\extensions\TemporalKit\scripts\berry_utility.py", line 641, in extract_frames_movpie
    video_stream = next((stream for stream in video_info['streams'] if stream['codec_type'] == 'video'), None)
TypeError: 'NoneType' object is not subscriptable
 installed and available in your system's PATH.

**Comment by aulerius** [comment]
I still get this error with ffmpeg installed.

I verify by running "ffmpeg" in any dir:
![image](https://github.com/CiaraStrawberry/TemporalKit/assets/51526300/ae122ecb-5c70-492c-a9d6-af5fa77120f0)

**Comment by orenodinner** [comment]
i am also getting the same error

**Comment by molkemon** [comment]
Same here, ffmpeg is in path and runs from any location in cmd, but the error still occurs.

**Comment by aulerius** [comment]
> Same here, ffmpeg is in path and runs from any location in cmd, but the error still occurs.
> 
> Edit: never mind I figured it out. I just put the ffmpeg.exe in the pathed folder, but what is actually required from the calling script is ffprobe which is part of the full ffmpeg package. So make sure to put ffprobe in the path aswell...

Nice! Would be helpful if this specific dependency was explicitly mentioned in readme or in these errors.

**Comment by aulerius** [comment]
@CiaraStrawberry Could you suggest any ways to troubleshoot this or look into this? I'd be very appreciated.
I've confirmed that I have ffmpeg, probe and play installed and working through PATH in other scenarios.

**Comment by mrgntamayo** [comment]
@orenodinner I also used this fix successfully.  It makes me wonder if it's an issue with the venv settings.

**Comment by salva133** [comment]
Have the same issue. I updated ffmpeg to the latest version, ensured that ffprobe is in the bin and even implemented the suggestion by orenodinner. No success. The traceback:

```
Please ensure that ffmpeg is installed and available in your system's PATH.
Traceback (most recent call last):
  File "F:\SD WebUI\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\SD WebUI\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\SD WebUI\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\SD WebUI\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\SD WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\SD WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\SD WebUI\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 117, in preprocess_video
    image = General_SD.generate_squares_to_folder(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side,max_frames=max_frames, output_folder=output_path,border=border_frames, ebsynth_mode=True,max_frames_to_save=max_frames)
  File "F:\SD WebUI\extensions\TemporalKit\scripts\Berry_Method.py", line 222, in generate_squares_to_folder
    frames = utilityb.extract_frames_movpie(video_data, fps, max_frames,False)
  File "F:\SD WebUI\extensions\TemporalKit\scripts\berry_utility.py", line 641, in extract_frames_movpie
    video_stream = next((stream for stream in video_info['streams'] if stream['codec_type'] == 'video'), None)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by trxsudo** [comment]
> Same here, ffmpeg is in path and runs from any location in cmd, but the error still occurs.
> 
> Edit: never mind I figured it out. I just put the ffmpeg.exe in the pathed folder, but what is actually required from the calling script is ffprobe which is part of the full ffmpeg package. So make sure to put ffprobe in the path aswell...

could you specify how you did that? i have put all three files in c:/path and changed variables. what else needs to be done?

**Comment by orenodinner** [comment]
From the error message I was able to identify the offending file and line.If there is no berry_utility.py, please write an error message.

**Comment by xxristoskk** [comment]
I found berry_utility.py and made the changes above, but I'm still getting the same error. I'm a bit confused, because ffmpeg is definitely in my path--I have other software that uses it as well.

Here is the full error:
reading video file... C:\Users\kingj\AppData\Local\Temp\gradio\21dbf8f77544e4cd7307db620d7a77421ef3a915\20230615143438.mp4
Interpolating extra frames with max frames 100 and interpolating = False
Error: [WinError 2] The system cannot find the file specified. Please ensure that ffmpeg is installed and available in your system's PATH.
Traceback (most recent call last):
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "S:\AUTOMATIC1111\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "S:\AUTOMATIC1111\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 117, in preprocess_video
    image = General_SD.generate_squares_to_folder(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side,max_frames=max_frames, output_folder=output_path,border=border_frames, ebsynth_mode=True,max_frames_to_save=max_frames)
  File "S:\AUTOMATIC1111\webui\extensions\TemporalKit\scripts\Berry_Method.py", line 222, in generate_squares_to_folder
    frames = utilityb.extract_frames_movpie(video_data, fps, max_frames,False)
  File "S:\AUTOMATIC1111\webui\extensions\TemporalKit\scripts\berry_utility.py", line 641, in extract_frames_movpie
    video_stream = next((stream for stream in video_info['streams'] if stream['codec_type'] == 'video'), None)
TypeError: 'NoneType' object is not subscriptable

**Comment by orenodinner** [comment]
I was getting 621 instead of 641 as an error. The problem between you and me seems to be another phenomenon. From reading the error message, it seems there is a problem with the video file.

**Comment by xxristoskk** [comment]
Oh, thanks for pointing that out! Turns out I was using the wrong height resolution.

**Comment by alexbofa** [comment]
Hello, I have the same problem.

### What happened?
Doesn't work in [Portable Stable Diffusion](https://github.com/serpotapov/stable-diffusion-portable#portable-stable-diffusion). See the console below.

### Steps to reproduce the problem

1. Drop video Pre-Processing > Input Video
2. Enter the path in the **Target Folder**
3. Press run

I've tried with all the different video formats, but to no avail
### Commit where the problem happens

[baf6946e06249c5af9851c60171692c44ef633e0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/baf6946e06249c5af9851c60171692c44ef633e0)

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --autolaunch
```


### List of extensions

![extentions](https://github.com/CiaraStrawberry/TemporalKit/assets/58225118/8f3184dc-9f92-4ef5-b749-0dee0b9aa4d6)


### Console logs

```venv "venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: <none>
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements
Installing requirements for TemporalKit extension

Launching Web UI with arguments: --xformers --autolaunch
Loading weights [9aba26abdf] from E:\Portable-Stable-Diffusion\models\Stable-diffusion\1111---\Deliberate.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\Portable-Stable-Diffusion\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Startup time: 7.9s (import torch: 1.8s, import gradio: 1.3s, import ldm: 0.5s, other imports: 1.1s, load scripts: 2.2s, create ui: 0.5s, gradio launch: 0.4s).
DiffusionWrapper has 859.52 M params.
Applying optimization: xformers... done.
Textual inversion embeddings loaded(0):
Model loaded in 4.7s (load weights from disk: 0.8s, create model: 0.8s, apply weights to model: 0.9s, apply half(): 0.4s, move model to device: 0.6s, load textual inversion embeddings: 1.2s).
reading video file... E:\Portable-Stable-Diffusion\tmp\gradio\a4c1ad7ccac87d19e24af25ba34167f0c583a811\input_video.mp4
Interpolating extra frames with max frames 20 and interpolating = False
Error: [WinError 2] The system cannot find the file specified. Please ensure that ffmpeg is installed and available in your system's PATH.
Traceback (most recent call last):
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Portable-Stable-Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Portable-Stable-Diffusion\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 121, in preprocess_video
    image = General_SD.generate_square_from_video(video,fps=fps,batch_size=batch_size, resolution=resolution,size_size=per_side )
  File "E:\Portable-Stable-Diffusion\extensions\TemporalKit\scripts\Berry_Method.py", line 179, in generate_square_from_video
    frames = utilityb.extract_frames_movpie(video_data, fps, frames_limit)
  File "E:\Portable-Stable-Diffusion\extensions\TemporalKit\scripts\berry_utility.py", line 641, in extract_frames_movpie
    video_stream = next((stream for stream in video_info['streams'] if stream['codec_type'] == 'video'), None)
TypeError: 'NoneType' object is not subscriptable
```
### Availability of variables via the console
**C:\Users\Admin>ffmpeg**
```
ffmpeg version 2023-06-15-git-41229ef705-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 13.100 / 58. 13.100
  libavcodec     60. 18.100 / 60. 18.100
  libavformat    60.  6.100 / 60.  6.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```
**C:\Users\Admin>ffprobe**
```
ffprobe version 2023-06-15-git-41229ef705-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 13.100 / 58. 13.100
  libavcodec     60. 18.100 / 60. 18.100
  libavformat    60.  6.100 / 60.  6.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] INPUT_FILE

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.
```

**C:\Users\Admin>python**
```
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

### Additional information

I tried this [method](https://github.com/CiaraStrawberry/TemporalKit/issues/40#issuecomment-1548077213), doesn't work.
```
cmd = ['C:\ffmpeg\ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_streams', video_path]
```

**Comment by alexbofa** [comment]
I solved this problem by replacing one version of [ffmpeg](https://github.com/GyanD/codexffmpeg/releases) with [another](https://github.com/AnimMouse/ffmpeg-autobuild/releases).

**Comment by iamkelatar** [comment]
Also getting this problem.  Followed exact setup steps, and ffmpeg is visible from any directory.  Tried replacing with exact path name in the utility file as well, but the error persists.

**Comment by alexbofa** [comment]
> Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.

I wrote a solution above, try it

**Comment by iamkelatar** [comment]
> > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> 
> I wrote a solution above, try it

I tried that as well.

What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution.  I'm uncertain why ffprobe is not visible within the context of the command line.  I've written an API and a console application that call ffmpeg without specifying the full path.  Additionally, I've verified that the path is both in my system and user environment variable.  I tried even specifying the exact ffprobe path in the the utility file.  I think maybe it's something permissions related?  My SD install is on a separate drive from my ffmpeg deployment.  However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.

**Comment by Hadrien-Estela** [comment]
Hello. If you use the released version of stable diffusion webui, the run.bat script load the environment.bat script that setup the path for the execution environment. So your custom path is not used, a new one is defined.
- install ffmpeg/ in the system directory at the root location of your stable diffution installation
-  in the environment.bat append '%DIR%\ffmpeg' to the PATH variable

**Comment by abhish2** [comment]
> > > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> > 
> > 
> > I wrote a solution above, try it
> 
> I tried that as well.
> 
> What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution. I'm uncertain why ffprobe is not visible within the context of the command line. I've written an API and a console application that call ffmpeg without specifying the full path. Additionally, I've verified that the path is both in my system and user environment variable. I tried even specifying the exact ffprobe path in the the utility file. I think maybe it's something permissions related? My SD install is on a separate drive from my ffmpeg deployment. However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.

where did you paste?

**Comment by CmpveYoo** [comment]
> > > > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> > > 
> > > 
> > > I wrote a solution above, try it
> > 
> > 
> > I tried that as well.
> > What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution. I'm uncertain why ffprobe is not visible within the context of the command line. I've written an API and a console application that call ffmpeg without specifying the full path. Additionally, I've verified that the path is both in my system and user environment variable. I tried even specifying the exact ffprobe path in the the utility file. I think maybe it's something permissions related? My SD install is on a separate drive from my ffmpeg deployment. However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.
> 
> where did you paste?

I tried a very dumb way , put ffprobe.exe to 
**SD root folder** 
 **SD root folder\system** 
 **SD root folder\webui**
and worked for now

i think [Hadrien-Estela](https://github.com/Hadrien-Estela) is right , there is something related to the environment.bat file

**Comment by xxristoskk** [comment]
Back again. I recently did a fresh install of the web ui and after following my previous solution, I'm getting the same error at line 641. I tried everything listed here, including appending the PATH in environment.bat, but the only thing that worked was moving ffprobe to the root folder. There's gotta be a way to point ui environment to a custom path.

**Comment by swingppx** [comment]
> 

Thanks a lot, the dumb way finally worked for me, every other attempt failed

**Comment by swingppx** [comment]
> > > > > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> > > > 
> > > > 
> > > > I wrote a solution above, try it
> > > 
> > > 
> > > I tried that as well.
> > > What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution. I'm uncertain why ffprobe is not visible within the context of the command line. I've written an API and a console application that call ffmpeg without specifying the full path. Additionally, I've verified that the path is both in my system and user environment variable. I tried even specifying the exact ffprobe path in the the utility file. I think maybe it's something permissions related? My SD install is on a separate drive from my ffmpeg deployment. However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.
> > 
> > 
> > where did you paste?
> 
> I tried a very dumb way , put ffprobe.exe to **SD root folder** **SD root folder\system** **SD root folder\webui** and worked for now
> 
> i think [Hadrien-Estela](https://github.com/Hadrien-Estela) is right , there is something related to the environment.bat file


Thanks a lot, the dumb way finally worked for me, every other attempt failed

**Comment by mrbianchi** [comment]
Following 

> > > > > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> > > > 
> > > > 
> > > > I wrote a solution above, try it
> > > 
> > > 
> > > I tried that as well.
> > > What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution. I'm uncertain why ffprobe is not visible within the context of the command line. I've written an API and a console application that call ffmpeg without specifying the full path. Additionally, I've verified that the path is both in my system and user environment variable. I tried even specifying the exact ffprobe path in the the utility file. I think maybe it's something permissions related? My SD install is on a separate drive from my ffmpeg deployment. However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.
> > 
> > 
> > where did you paste?
> 
> I tried a very dumb way , put ffprobe.exe to **SD root folder** **SD root folder\system** **SD root folder\webui** and worked for now
> 
> i think [Hadrien-Estela](https://github.com/Hadrien-Estela) is right , there is something related to the environment.bat file

sdroot/system [is enough](https://stackoverflow.com/a/65860115) , now is working for me, thanks

**Comment by Niceceday** [comment]
I had the same issue, entering cmd in any directory recognizes ffmpeg etc. Then I put everything into the path and it solved the problem.
![image](https://github.com/CiaraStrawberry/TemporalKit/assets/58141173/262c3b1c-5b80-4e90-b200-582e0fc11a18)

**Comment by xiohulp** [comment]
> When I directly input the address without using a path, it seems to work for now. cmd = ['C:\path\ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_streams', video_path]
> 
> https://github.com/CiaraStrawberry/TemporalKit/blob/504774d999861ca9d711ece91c78bf9eff5d312f/scripts/berry_utility.py#L621

is it ok if i rewrite as such  cmd = ['D:\ffmpeg\bin\ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_streams', video_path]

**Comment by JamesMasino** [comment]
> > > Also getting this problem. Followed exact setup steps, and ffmpeg is visible from any directory. Tried replacing with exact path name in the utility file as well, but the error persists.
> > 
> > 
> > I wrote a solution above, try it
> 
> I tried that as well.
> 
> What I ended up doing was just copying ffprobe to the webui directory in automatic1111, which is a dumb but working solution. I'm uncertain why ffprobe is not visible within the context of the command line. I've written an API and a console application that call ffmpeg without specifying the full path. Additionally, I've verified that the path is both in my system and user environment variable. I tried even specifying the exact ffprobe path in the the utility file. I think maybe it's something permissions related? My SD install is on a separate drive from my ffmpeg deployment. However, I also tried running the SD web ui under administrator credentials on windows 11, but that didn't fix the issue.

Adding that this worked for me, my SD webui folder is also on a separate drive to my C's root folder where ffmpeg is. This might be the issue for others where this is the case.

Again the solution for the line 641 error for me:
- Copy ffprobe.exe to the stable-diffusion-webui directory

**Comment by Fivefold** [comment]
A non-hacky solution is modifying `environment.bat` by appending `;%PATH%` to the end of the `set PATH=` line. This will make it search for ffmpeg (and a bunch of other stuff) within the stated directories and if it can't find it, it will search in the system PATH (the one you set in Windows). If `%PATH%` it is missing it will not use the system PATH and only the stated directories:

```bat
@echo off

set DIR=%~dp0system

set PATH=C:\Windows\system32;C:\Windows;%DIR%\git\bin;%DIR%\python;%DIR%\python\Scripts;%PATH%
set PY_LIBS=%DIR%\python\Scripts\Lib;%DIR%\python\Scripts\Lib\site-packages
set PY_PIP=%DIR%\python\Scripts
set SKIP_VENV=1
set PIP_INSTALLER_LOCATION=%DIR%\python\get-pip.py
set TRANSFORMERS_CACHE=%DIR%\transformers-cache
```

**Comment by TheSketty** [comment]
> Hello. If you use the released version of stable diffusion webui, the run.bat script load the environment.bat script that setup the path for the execution environment. So your custom path is not used, a new one is defined.
> 
>     * install ffmpeg/ in the system directory at the root location of your stable diffution installation
> 
>     * in the environment.bat append '%DIR%\ffmpeg' to the PATH variable

Wait, is this applied to SD Forge? What about A1111?
