### ISSUE TITLE
error at step "read_last_settings"

### ISSUE THREAD

**Issue by Dankmank** [CiaraStrawberry/TemporalKit#43]
When i pressed read last settings, i got errors everywhere on the screen and this:

batch settings exists = True
reading path at G:\AI\stable-diffusion-webui\outputs\temporalkit\batch_settings.txt
Traceback (most recent call last):
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\AI\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 341, in update_settings_from_file
    fps = int(f.readline().strip())
ValueError: invalid literal for int() with base 10: '30.0'

Does anyone know, whats going on here? Thanks in advance!

**Comment by CiaraStrawberry** [comment]
O.o oh my bad, lemme fix that

**Comment by CiaraStrawberry** [comment]
looks like i misread the docs on gradio.number precision, update and this should be fixed in the future ^^

**Comment by Jetbleu** [comment]
I'm getting a similar error while trying to do the EBSynth Split video method after pressing the "read_last_settings". I have the latest update until this date May 5, 2023 

Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 361, in save_settings
