### ISSUE TITLE
fps  real number, not None

### ISSUE THREAD

**Issue by kaosbeat** [CiaraStrawberry/TemporalKit#45]
I say there was a commit involving fps = int(fps)

I'm getting 

```
[MoviePy] >>>> Building video /home/kaos/Documents/AI/alfred/preproces/blended.mp4
[MoviePy] Writing video /home/kaos/Documents/AI/alfred/preproces/blended.mp4
Traceback (most recent call last):
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/kaos/stable-diffusion-webui/extensions/TemporalKit/scripts/sd-TemporalKit-UI.py", line 137, in apply_image_to_vide_batch
    return General_SD.process_video_batch(video_path_old=video,fps=fps,per_side=per_side,batch_size=batch_size,fillindenoise=0,edgedenoise=0,_smol_resolution=output_resolution,square_textures=images,max_frames=max_frames,output_folder=input_folder,border=border_frames)
  File "/home/kaos/stable-diffusion-webui/extensions/TemporalKit/scripts/Berry_Method.py", line 319, in process_video_batch
    generated_vid = utilityb.pil_images_to_video(combined,save_loc, fps)
  File "/home/kaos/stable-diffusion-webui/extensions/TemporalKit/scripts/berry_utility.py", line 512, in pil_images_to_video
    clip.write_videofile(output_file,fps,codec='libx264')
  File "/home/kaos/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/kaos/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/home/kaos/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/video/VideoClip.py", line 342, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 201, in ffmpeg_write_video
    writer = FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "/home/kaos/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 86, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not NoneType
```

But I'm not syure if it is related?

**Comment by HzTTT** [comment]
To update your pip package,it work for me 

`pip install moviepy --upgrade`
