### ISSUE TITLE
recombining ebsynth not successful

### ISSUE THREAD

**Issue by trxsudo** [CiaraStrawberry/TemporalKit#57]
saving at frame 42
saved to D:\temporal Kit\pd 4\4\keys\keys00042.png at size (720, 1280)
40
saving at frame 47
saved to D:\temporal Kit\pd 4\4\keys\keys00047.png at size (720, 1280)
40
saving at frame 52
saved to D:\temporal Kit\pd 4\4\keys\keys00052.png at size (720, 1280)
40
saving at frame 57
saved to D:\temporal Kit\pd 4\4\keys\keys00057.png at size (720, 1280)
[2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97]
Traceback (most recent call last):
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\supercupid\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\supercupid\sd-webui-aki-v4.1\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 196, in recombine_ebsynth
    new_video =  ebsynth.crossfade_folder_of_folders(folder_loc,fps=fps)
  File "D:\supercupid\sd-webui-aki-v4.1\extensions\TemporalKit\scripts\Ebsynth_Processing.py", line 134, in crossfade_folder_of_folders
    current_dir = os.path.join(root_folder, dirs[0])
IndexError: list index out of range

gave me this message. everything before this was fine (i think). running ebsynth.exe "run all" was smoothly. what went wrong?

**Comment by Wingie** [comment]
same issue +1

**Comment by CarlosReyes99** [comment]
I have the same error

**Comment by HotRod888** [comment]
same

**Comment by Noire9000** [comment]
Same.. Someone solved ?

**Comment by JustCann** [comment]
I have the same issue :( just doing it manually for now.

**Comment by majorsauce** [comment]
Have you all executed EbSynth on each individual keyframe folder ? 
Eg. you initially run it for the keys/frames folders in root/0 but then you also have to run it against keys/frames of root/1 and root/2...
Also looks like EbSynth does not allow to change the project dir once set, so therefor all out_xxx folder will be generated in root/0, this seems to be correct behaviour.
