### ISSUE TITLE
Error while prepare ebsynth

### ISSUE THREAD

**Issue by drowi2001** [CiaraStrawberry/TemporalKit#58]
from Resolution 640X360 video
per side: 3 to 1920X1080 Resolution
when i  set Output Resolution:640,360 or 1280,720 or 1920,1080 , have the same issue, what's it mean?

frames num = 117 while num batches = 3
batch 0 has 54 frames
batch 1 has 54 frames
batch 2 has 9 frames
3
0
saving at frame 3
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/TemporalKit/scripts/sd-TemporalKit-UI.py", line 145, in post_process_ebsynth
    return ebsynth.sort_into_folders(video_path=video,fps=fps,per_side=per_side,batch_size=batch_size,_smol_resolution=output_resolution,square_textures=images,max_frames=max_frames,output_folder=input_folder,border=border_frames)
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/TemporalKit/scripts/Ebsynth_Processing.py", line 88, in sort_into_folders
    bmethod.save_square_texture(frame_to_save, os.path.join(output_keys_folder, "keys{:05d}.png".format(frame_position)))
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/TemporalKit/scripts/Berry_Method.py", line 155, in save_square_texture
    raise ValueError("Invalid texture shape. Expected a 3-channel RGB image.")
ValueError: Invalid texture shape. Expected a 3-channel RGB image.

**Comment by hunfer11** [comment]
Sorry for asking you, How did you fix this? Or it still exist?

**Comment by j238** [comment]
Is your output files output by something other than Stable Diffusion?
If so re-output your files with Stable Diffusion.
Setting images to `Denoising strength: 0` will output same images.
(img2img Batch can be used)
I got around the problem with the above method.
