### ISSUE TITLE
Unable to load the extension after first use.

### ISSUE THREAD

**Issue by ampple** [CiaraStrawberry/TemporalKit#6]
Had no trouble playing with the extension after my first use and then i run into this error message while trying to relaunch auto1111:

Error loading script: Berry_Method.py
Traceback (most recent call last):
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 8, in <module>
    from moviepy.editor import *
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\VideoClip.py", line 21, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 11, in <module>
    from moviepy.config import get_setting
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\config.py", line 34, in <module>
    from imageio.plugins.ffmpeg import get_exe
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\ffmpeg.py", line 143, in <module>
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'

Error loading script: sd-TemporalKit-UI.py
Traceback (most recent call last):
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 40, in <module>
    import scripts.Berry_Method as berry
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\extensions\TemporalKit\scripts\Berry_Method.py", line 8, in <module>
    from moviepy.editor import *
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\VideoClip.py", line 21, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 11, in <module>
    from moviepy.config import get_setting
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\moviepy\config.py", line 34, in <module>
    from imageio.plugins.ffmpeg import get_exe
  File "D:\StableDiffusion\Auto1111\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\ffmpeg.py", line 143, in <module>
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'

______________________________________________________________________________________________________________________________________________

I was able to get it to run again with a fresh install of auto1111, then ran into the same exact issue when relaunching.

**Comment by CiaraStrawberry** [comment]
cd into "stable-diffusion-webui\venv\Scripts", run "pip install imageio_ffmpeg"

**Comment by ampple** [comment]
Ahh yes, thank you! I was installing into the wrong directory!!!!!

**Comment by CiaraStrawberry** [comment]
Perfect, drop a message if you have any further issues :D
Added a commit that should fix this for anyone in the future too.
