### ISSUE TITLE
BUG [ Error]

### ISSUE THREAD

**Issue by p0mad** [CiaraStrawberry/TemporalKit#74]
Traceback (most recent call last):
  File "D:\sl\q\launch.py", line 39, in <module>
    main()
  File "D:\sl\q\launch.py", line 35, in main       
    start()
  File "D:\sl\q\modules\launch_utils.py", line 390, in start
    import webui
  File "D:\sl\q\webui.py", line 39, in <module>    
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them  
  File "D:\sl\q\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\sl\q\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>     
    from pytorch_lightning.callbacks.batch_size_finder 
import BatchSizeFinder
  File "D:\sl\q\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "D:\sl\q\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>     
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "D:\sl\q\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>        
    from torchmetrics import Metric
  File "D:\sl\q\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402  
  File "D:\sl\q\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 121, in <module>        
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "D:\sl\q\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 31, in <module>    
    from torchmetrics.functional.text.bert import bert_score
  File "D:\sl\q\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 25, in <module>        
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "D:\sl\q\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 27, 
in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase    
  File "D:\sl\q\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "D:\sl\q\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>   
    from .utils.versions import require_version, require_version_core
  File "D:\sl\q\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\sl\q\venv\lib\site-packages\transformers\utils\generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy       
  File "D:\sl\q\venv\lib\site-packages\transformers\utils\import_utils.py", line 34, in <module>
    from . import logging
  File "D:\sl\q\venv\lib\site-packages\transformers\utils\logging.py", line 31, in <module>
    from tqdm import auto as tqdm_lib
ImportError: cannot import name 'auto' from 'tqdm' (D:\sl\q\venv\lib\site-packages\tqdm\__init__.py)      
Press any key to continue . . .

**Comment by Combivision** [comment]
Hello, the same thing is happening to me, do you have any solution?

**Comment by Combivision** [comment]
:(  Help
 Installing requirements for TemporalKit extension

Launching Web UI with arguments: --autolaunch --xformers --ckpt-dir C:\MODELOS SD\models
Traceback (most recent call last):
  File "C:\Stable_Diffusion\stable-diffusion-webui\launch.py", line 39, in <module>
    main()
  File "C:\Stable_Diffusion\stable-diffusion-webui\launch.py", line 35, in main
    start()
  File "C:\Stable_Diffusion\stable-diffusion-webui\modules\launch_utils.py", line 390, in start
    import webui
  File "C:\Stable_Diffusion\stable-diffusion-webui\webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 121, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 31, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 25, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 34, in <module>
    from . import logging
  File "C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\logging.py", line 31, in <module>
    from tqdm import auto as tqdm_lib
ImportError: cannot import name 'auto' from 'tqdm' (C:\Stable_Diffusion\stable-diffusion-webui\venv\lib\site-packages\tqdm\__init__.py)
Press any key to continue . . .

**Comment by p0mad** [comment]
@Combivision 
Not yet, but you can remove the C:\Stable_Diffusion\stable-diffusion-webui\extensions\temporalkit
and also remove the C:\Stable_Diffusion\stable-diffusion-webui\
to be able to use your previous functionality with SD webUI!

But i've got notting to solve this.
