### ISSUE TITLE
Nothing shows up after installation ? 

### ISSUE THREAD

**Issue by ameen-roayan** [CiaraStrawberry/TemporalKit#8]
Hi ! 

I tried the installation through a1111 extensions tab, and the script does show in the scripts section but there is nothing there, and nothing happens if i click save, if i click move it takes me to a random tab depending on whats open 

![image](https://user-images.githubusercontent.com/92278134/232525877-09a7c8e8-1ec1-4160-955c-bbf88964fa4b.png)
![image](https://user-images.githubusercontent.com/92278134/232525930-657994cd-02b2-401e-bd3c-432afacd0353.png)

Also i am noticing this error in the cmd if i click save

RuntimeError: Event loop is closed
Startup time: 6.7s (load scripts: 1.7s, create ui: 4.3s, gradio launch: 0.1s, scripts app_started_callback: 0.5s).
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\TemporalKit\scripts\TemporalKitImg2ImgTab.py", line 31, in on_button_click
    save_image(lastimage, 'last.png', extension_folder)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\TemporalKit\scripts\TemporalKitImg2ImgTab.py", line 22, in save_image
    image.save(file_path)
AttributeError: 'NoneType' object has no attribute 'save'

**Comment by CiaraStrawberry** [comment]
ah, that script is a WIP tool that automatically moves images back to the temporalkit window if you have it open when you generate an image.

I'll have to add a label to tell people about that in the script to avoid this happening as I can see how you thought that.

The actual script should be in the top bar

**Comment by ameen-roayan** [comment]
Oh thanks for the clarification ! 
Its not showing in the top bar then.

**Comment by kianma42** [comment]
now what should we do???

**Comment by kianma42** [comment]
> ah, that script is a WIP tool that automatically moves images back to the temporalkit window if you have it open when you generate an image.
> 
> I'll have to add a label to tell people about that in the script to avoid this happening as I can see how you thought that.
> 
> The actual script should be in the top bar

please tell me how should i fix this
