### ISSUE TITLE
Error 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by EllNiko** [CiaraStrawberry/TemporalKit#96]
Can you help me? I don't understand what I did wrong, I do it like other people on YouTube, but I get this error:

Traceback (most recent call last):
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "S:\Neiro\SD 2.9\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "S:\Neiro\SD 2.9\sd.webui\webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 93, in preprocess_video
    existing_frames = [sd_utility.extract_frames_movpie(data, fps,max_frames=max_total_frames,perform_interpolation=False)]
  File "S:\Neiro\SD 2.9\sd.webui\webui\extensions\TemporalKit\scripts\berry_utility.py", line 641, in extract_frames_movpie
    video_stream = next((stream for stream in video_info['streams'] if stream['codec_type'] == 'video'), None)
TypeError: 'NoneType' object is not subscriptable

**Comment by liuqi008** [comment]
me too

**Comment by wysren** [comment]
check ffmpeg

**Comment by AdamShuo** [comment]
me 2
after i've installed the latest t-k
reading video file... C:\Users\ADMINI~1\AppData\Local\Temp\gradio\168bf085ba9b9bec856eee8288ad1595fff60d23\FILM.mp4
Interpolating extra frames with max frames 450000 and interpolating = False
video duration is 15.09
frame repeat is 0, target fps is 30 and original fps is 30.16
Extracted 452 frames at 30 fps over a clip with a length of 15.066666666666666 seconds with the old duration of 15.09 seconds
frame_groups 452
overlap group size 10
overlap group size 10
overlap group size 10
overlap group size 10
 trim_imagestransitions [0, 1, 2, 3]
frames_total_size = 6, frames batch size = 90 array length = 6
splitting video 0
[MoviePy] >>>> Building video F:\Projects\02\0\input_video.mp4
[MoviePy] Writing video F:\Projects\02\0\input_video.mp4
Traceback (most recent call last):
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\ProgramData\sd-webui-aki-v4.4\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py", line 96, in preprocess_video
    split_video_paths,transition_data = General_SD.split_videos_into_smaller_videos(max_keys,existing_frames,fps,max_frames,output_path,border_frames,split_based_on_cuts)
  File "F:\ProgramData\sd-webui-aki-v4.4\extensions\TemporalKit\scripts\Berry_Method.py", line 594, in split_videos_into_smaller_videos
    output_files.append(utilityb.pil_images_to_video(frames, new_video_loc, fps))
  File "F:\ProgramData\sd-webui-aki-v4.4\extensions\TemporalKit\scripts\berry_utility.py", line 512, in pil_images_to_video
    clip.write_videofile(output_file,fps,codec='libx264')
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\decorators.py", line 137, in use_clip_fps_by_default
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\decorator.py", line 232, in fun
    for i, extra in enumerate(extras):
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\video\VideoClip.py", line 342, in write_videofile
    Either 'bar' (progress bar) or None or any Proglog logger.
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 201, in ffmpeg_write_video
    audiofile=None, verbose=True, threads=None, ffmpeg_params=None,
  File "F:\ProgramData\sd-webui-aki-v4.4\python\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 86, in __init__
    '-s', '%dx%d' % (size[0], size[1]),
TypeError: must be real number, not NoneType

**Comment by snrtherock** [comment]
> overlap

Did you get the "Overlap Group Size" issue fixed?

**Comment by Dogath** [comment]
me too

**Comment by Dogath** [comment]
检查一下你ffmpeg的路径有没有设置对。有的时候即使你没有设置对，你在控制台打”ffmpeg“也看不出问题。路径要设置到那个含有三个exe的文件夹“bin”才可以正常运行
